//what does .default do?
const EarthImages = {
    0: require('./earth'+0+'.gif').default,
    1: require('./earth'+1+'.gif').default,
    2: require('./earth'+2+'.gif').default,
    3: require('./earth'+3+'.gif').default,
    4: require('./earth'+4+'.gif').default,
    5: require('./earth'+5+'.gif').default,
    6: require('./earth'+6+'.gif').default,
    7: require('./earth'+7+'.gif').default,
    8: require('./earth'+8+'.gif').default,
    9: require('./earth'+9+'.gif').default,
    10: require('./earth'+10+'.gif').default,
    11: require('./earth'+11+'.gif').default,
    12: require('./earth'+12+'.gif').default,
    13: require('./earth'+13+'.gif').default,
    14: require('./earth'+14+'.gif').default,
    15: require('./earth'+15+'.gif').default,
    16: require('./earth'+16+'.gif').default,
    17: require('./earth'+17+'.gif').default,
    18: require('./earth'+18+'.gif').default,
    19: require('./earth'+19+'.gif').default,
    20: require('./earth'+20+'.gif').default,
    21: require('./earth'+21+'.gif').default,
    22: require('./earth'+22+'.gif').default,
    23: require('./earth'+23+'.gif').default,
    24: require('./earth'+24+'.gif').default,
    25: require('./earth'+25+'.gif').default,
    26: require('./earth'+26+'.gif').default,
    27: require('./earth'+27+'.gif').default,
    28: require('./earth'+28+'.gif').default,
    29: require('./earth'+29+'.gif').default,
    30: require('./earth'+30+'.gif').default,
    31: require('./earth'+31+'.gif').default,
    32: require('./earth'+32+'.gif').default,
    33: require('./earth'+33+'.gif').default,
    34: require('./earth'+34+'.gif').default,
    35: require('./earth'+35+'.gif').default,
} 

export default EarthImages